#ifndef CONFIG_H
# define CONFIG_H

# define MANDEL_WINDOW_WIDTH  640
# define MANDEL_WINDOW_HEIGHT 480
# define MANDEL_WINDOW_TITLE "Mandelbrot"
# define MANDEL_SURFACE_DEPTH 8
# define MANDEL_ITERATIONS 20

#endif
